packages:
    asm89/stack-cors: 1.3.0
    behat/mink: v1.10.0
    behat/mink-goutte-driver: v1.3.0
    behat/mink-selenium2-driver: v1.6.0
    chi-teck/drupal-code-generator: 1.33.1
    composer/ca-bundle: 1.3.3
    composer/composer: 2.2.17
    composer/installers: v1.12.0
    composer/metadata-minifier: 1.0.0
    composer/pcre: 1.0.1
    composer/semver: 3.3.2
    composer/spdx-licenses: 1.5.7
    composer/xdebug-handler: 3.0.3
    consolidation/annotated-command: 4.5.6
    consolidation/config: 1.2.1
    consolidation/filter-via-dot-access-data: 1.0.0
    consolidation/log: 2.1.1
    consolidation/output-formatters: 4.2.2
    consolidation/robo: 3.0.10
    consolidation/self-update: 2.0.5
    consolidation/site-alias: 3.1.5
    consolidation/site-process: 4.2.0
    cweagans/composer-patches: 1.7.2
    dealerdirect/phpcodesniffer-composer-installer: v0.7.2
    dflydev/dot-access-data: v1.1.0
    dmore/chrome-mink-driver: 2.8.1
    doctrine/annotations: 1.13.3
    doctrine/cache: 1.13.0
    doctrine/collections: 1.6.8
    doctrine/common: 2.13.3
    doctrine/event-manager: 1.1.1
    doctrine/inflector: 1.4.4
    doctrine/instantiator: 1.4.1
    doctrine/lexer: 1.2.3
    doctrine/persistence: 1.3.8
    doctrine/reflection: 1.2.3
    drupal/a11yproject_checklist: 'dev-1.0.x:95e22a6b0ed2d1691359ca5641df2b0591c659b5'
    drupal/admin_toolbar: 3.1.1
    drupal/checklistapi: 2.1.0
    drupal/classy_paragraphs: 1.0.0-rc1
    drupal/coder: 8.3.15
    drupal/coffee: 1.2.0
    drupal/config_filter: 2.4.0
    drupal/config_split: 2.0.0-rc3
    drupal/core: 9.4.3
    drupal/core-composer-scaffold: 9.4.3
    drupal/core-dev: 9.4.3
    drupal/core-recommended: 9.4.3
    drupal/core-vendor-hardening: 9.4.3
    drupal/ctools: 3.9.0
    drupal/devel: 4.1.5
    drupal/easy_breadcrumb: 2.0.3
    drupal/editor_advanced_link: 2.0.0
    drupal/entity_reference_revisions: 1.9.0
    drupal/entity_usage: 2.0.0-beta6
    drupal/fancy_file_delete: 2.0.7
    drupal/field_group: 3.2.0
    drupal/google_analytics: 4.0.0
    drupal/hreflang: 1.9.0
    drupal/key: 1.15.0
    drupal/launch_checklist: 1.1.5
    drupal/linkit: 5.0.0-beta13
    drupal/menu_link_attributes: 1.2.0
    drupal/metatag: 1.21.0
    drupal/metatag_google_plus: 1.21.0
    drupal/metatag_open_graph: 1.21.0
    drupal/metatag_twitter_cards: 1.21.0
    drupal/metatag_verification: 1.21.0
    drupal/minifyhtml: 2.0.1
    drupal/minifyjs: 2.2.0
    drupal/paragraphs: 1.14.0
    drupal/pathauto: 1.10.0
    drupal/redirect: 1.7.0
    drupal/redis: 1.5.0
    drupal/resource_hints: 'dev-1.x:c6ddff3452d3028e7b6e97bb937109f74e310555'
    drupal/schema_metatag: 2.3.0
    drupal/schema_web_site: 2.3.0
    drupal/search_api: 1.25.0
    drupal/search_api_solr: 4.2.8
    drupal/seckit: 2.0.0
    drupal/seo_checklist: 'dev-4.x:443de092b2cc1c020c2612f445a989ded62d056b'
    drupal/seo_starter: 'dev-1.x:ac4eac7dcf9fa87551846cb629df4e68fa96b9cc'
    drupal/simple_sitemap: 4.1.2
    drupal/sitemap: 2.0.0-beta3
    drupal/token: 1.10.0
    drupal/tour_enhancements: 1.0.0
    drupal/tour_ui: 1.0.0-rc1
    drupal/twig_vardumper: 3.0.2
    drupal/upgrade_status: 3.11.0
    drupal/views_bulk_operations: 4.1.4
    drupal/webp: 1.0.0-beta6
    drupal/yoast_seo: 1.7.0
    drupal/youtube: 1.2.0
    drush/drush: 10.6.2
    easyrdf/easyrdf: 1.1.1
    egulias/email-validator: 3.2.1
    enlightn/security-checker: v1.10.0
    fabpot/goutte: v3.3.1
    friends-of-behat/mink-browserkit-driver: v1.6.1
    grasmash/expander: 1.0.0
    grasmash/yaml-expander: 1.4.0
    guzzlehttp/guzzle: 6.5.8
    guzzlehttp/promises: 1.5.1
    guzzlehttp/psr7: 1.9.0
    instaclick/php-webdriver: 1.4.14
    joachim-n/composer-manifest: 1.1.4
    justinrainbow/json-schema: 5.2.12
    laminas/laminas-diactoros: 2.11.3
    laminas/laminas-escaper: 2.9.0
    laminas/laminas-feed: 2.17.0
    laminas/laminas-servicemanager: 3.16.0
    laminas/laminas-stdlib: 3.7.1
    laminas/laminas-text: 2.9.0
    league/container: 3.4.1
    maennchen/zipstream-php: 2.2.1
    masterminds/html5: 2.7.5
    mathieuviossat/arraytotexttable: v1.0.8
    mglaman/phpstan-drupal: 0.12.15
    mikey179/vfsstream: v1.6.11
    myclabs/deep-copy: 1.11.0
    myclabs/php-enum: 1.8.3
    nette/finder: v2.5.3
    nette/utils: v3.2.7
    nikic/php-parser: v4.14.0
    oomphinc/composer-installers-extender: 2.0.0
    palantirnet/drupal-rector: 0.11.4
    pantheon-systems/drupal-integrations: 9.0.3
    pantheon-systems/search_api_pantheon: 3.0.1
    patchwork/jsqueeze: v2.0.5
    pear/archive_tar: 1.4.14
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.11
    pear/pear_exception: v1.0.2
    phar-io/manifest: 2.0.3
    phar-io/version: 3.2.1
    phpdocumentor/reflection-common: 2.2.0
    phpdocumentor/reflection-docblock: 5.3.0
    phpdocumentor/type-resolver: 1.6.1
    phpspec/prophecy: v1.15.0
    phpspec/prophecy-phpunit: v2.0.1
    phpstan/extension-installer: 1.1.0
    phpstan/phpdoc-parser: 1.6.4
    phpstan/phpstan: 0.12.99
    phpstan/phpstan-deprecation-rules: 0.12.6
    phpunit/php-code-coverage: 9.2.15
    phpunit/php-file-iterator: 3.0.6
    phpunit/php-invoker: 3.1.1
    phpunit/php-text-template: 2.0.4
    phpunit/php-timer: 5.0.3
    phpunit/phpunit: 9.5.21
    psr/cache: 1.0.1
    psr/container: 1.1.2
    psr/event-dispatcher: 1.0.0
    psr/http-client: 1.0.1
    psr/http-factory: 1.0.1
    psr/http-message: 1.0.1
    psr/log: 1.1.4
    psy/psysh: v0.10.12
    ralouphie/getallheaders: 3.0.3
    react/promise: v2.9.0
    rector/rector: 0.11.60
    rvtraveller/qs-composer-installer: '1.2'
    sebastian/cli-parser: 1.0.1
    sebastian/code-unit: 1.0.8
    sebastian/code-unit-reverse-lookup: 2.0.3
    sebastian/comparator: 4.0.6
    sebastian/complexity: 2.0.2
    sebastian/diff: 4.0.4
    sebastian/environment: 5.1.4
    sebastian/exporter: 4.0.4
    sebastian/global-state: 5.0.5
    sebastian/lines-of-code: 1.0.3
    sebastian/object-enumerator: 4.0.4
    sebastian/object-reflector: 2.0.4
    sebastian/recursion-context: 4.0.4
    sebastian/resource-operations: 3.0.3
    sebastian/type: 3.0.0
    sebastian/version: 3.0.2
    seld/jsonlint: 1.9.0
    seld/phar-utils: 1.2.0
    sirbrillig/phpcs-variable-analysis: v2.11.4
    slevomat/coding-standard: 7.2.1
    solarium/solarium: 6.2.6
    squizlabs/php_codesniffer: 3.7.1
    stack/builder: v1.0.6
    symfony-cmf/routing: 2.3.4
    symfony/browser-kit: v4.4.37
    symfony/console: v4.4.43
    symfony/css-selector: v4.4.37
    symfony/debug: v4.4.41
    symfony/dependency-injection: v4.4.43
    symfony/deprecation-contracts: v2.5.2
    symfony/dom-crawler: v4.4.42
    symfony/error-handler: v4.4.41
    symfony/event-dispatcher: v4.4.42
    symfony/event-dispatcher-contracts: v1.1.13
    symfony/filesystem: v4.4.42
    symfony/finder: v4.4.41
    symfony/http-client-contracts: v2.5.2
    symfony/http-foundation: v4.4.43
    symfony/http-kernel: v4.4.43
    symfony/lock: v4.4.40
    symfony/mime: v5.4.10
    symfony/phpunit-bridge: v5.4.10
    symfony/polyfill-ctype: v1.25.0
    symfony/polyfill-iconv: v1.25.0
    symfony/polyfill-intl-idn: v1.25.0
    symfony/polyfill-intl-normalizer: v1.25.0
    symfony/polyfill-mbstring: v1.25.0
    symfony/polyfill-php72: v1.26.0
    symfony/polyfill-php73: v1.26.0
    symfony/polyfill-php80: v1.25.0
    symfony/process: v4.4.41
    symfony/psr-http-message-bridge: v2.1.2
    symfony/routing: v4.4.41
    symfony/serializer: v4.4.43
    symfony/service-contracts: v2.5.2
    symfony/translation: v4.4.41
    symfony/translation-contracts: v2.5.2
    symfony/validator: v4.4.43
    symfony/var-dumper: v5.4.9
    symfony/yaml: v4.4.43
    textalk/websocket: 1.5.8
    theseer/tokenizer: 1.2.1
    twig/twig: v2.15.1
    typo3/phar-stream-wrapper: v3.1.7
    webflo/drupal-finder: 1.2.2
    webmozart/assert: 1.11.0
    webmozart/path-util: 2.3.0
    weitzman/drupal-test-traits: 1.6.0
