packages:
    asm89/stack-cors: v2.2.0
    behat/mink: v1.11.0
    behat/mink-browserkit-driver: v2.2.0
    behat/mink-selenium2-driver: v1.7.0
    chi-teck/drupal-code-generator: 3.3.0
    colinodell/psr-testlogger: v1.3.0
    composer/ca-bundle: 1.4.0
    composer/class-map-generator: 1.1.0
    composer/composer: 2.7.1
    composer/installers: v1.12.0
    composer/metadata-minifier: 1.0.0
    composer/pcre: 3.1.1
    composer/semver: 3.4.0
    composer/spdx-licenses: 1.5.8
    composer/xdebug-handler: 3.0.3
    consolidation/annotated-command: 4.9.2
    consolidation/config: 2.1.2
    consolidation/filter-via-dot-access-data: 2.0.2
    consolidation/log: 3.0.0
    consolidation/output-formatters: 4.3.2
    consolidation/robo: 4.0.6
    consolidation/self-update: 2.2.0
    consolidation/site-alias: 4.0.1
    consolidation/site-process: 5.2.0
    cweagans/composer-patches: 1.7.3
    dealerdirect/phpcodesniffer-composer-installer: v1.0.0
    dflydev/dot-access-data: v3.0.2
    doctrine/annotations: 1.14.3
    doctrine/common: 3.4.3
    doctrine/deprecations: 1.1.3
    doctrine/event-manager: 2.0.0
    doctrine/instantiator: 2.0.0
    doctrine/lexer: 2.1.1
    doctrine/persistence: 3.2.0
    drupal/coder: 8.3.23
    drupal/core: 10.2.3
    drupal/core-composer-scaffold: 10.2.3
    drupal/core-dev: 10.2.3
    drupal/core-recommended: 10.2.3
    drupal/core-vendor-hardening: 10.2.3
    drupal/devel: 5.1.2
    drush/drush: 12.4.3
    egulias/email-validator: 4.0.2
    ewcomposer/unpack: 'dev-master:3654c2990203584c56ac99eadeaf2c092a56162d'
    google/protobuf: v3.25.2
    grasmash/expander: 3.0.0
    grasmash/yaml-cli: 3.1.0
    guzzlehttp/guzzle: 7.8.1
    guzzlehttp/promises: 2.0.2
    guzzlehttp/psr7: 2.6.2
    instaclick/php-webdriver: 1.4.18
    joachim-n/composer-manifest: 1.1.5
    justinrainbow/json-schema: v5.2.13
    kanopi/shrubs: 0.2.8
    league/container: 4.2.0
    masterminds/html5: 2.8.1
    mck89/peast: v1.15.4
    mglaman/phpstan-drupal: 1.2.7
    micheh/phpcs-gitlab: 1.1.0
    mikey179/vfsstream: v1.6.11
    myclabs/deep-copy: 1.11.1
    nikic/php-parser: v5.0.0
    oomphinc/composer-installers-extender: 2.0.0
    open-telemetry/api: 1.0.3
    open-telemetry/context: 1.0.2
    open-telemetry/exporter-otlp: 1.0.3
    open-telemetry/gen-otlp-protobuf: 1.1.0
    open-telemetry/sdk: 1.0.8
    open-telemetry/sem-conv: 1.24.0
    palantirnet/drupal-rector: 0.19.2
    pantheon-systems/drupal-integrations: 10.0.1
    pear/archive_tar: 1.4.14
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.14
    pear/pear_exception: v1.0.2
    phar-io/manifest: 2.0.3
    phar-io/version: 3.2.1
    phootwork/collection: v3.2.2
    phootwork/lang: v3.2.2
    php-http/discovery: 1.19.2
    php-http/guzzle7-adapter: 1.0.0
    php-http/httplug: 2.4.0
    php-http/promise: 1.3.0
    phpdocumentor/reflection-common: 2.2.0
    phpdocumentor/reflection-docblock: 5.3.0
    phpdocumentor/type-resolver: 1.8.0
    phpowermove/docblock: v4.0
    phpspec/prophecy: v1.18.0
    phpspec/prophecy-phpunit: v2.1.0
    phpstan/extension-installer: 1.3.1
    phpstan/phpdoc-parser: 1.25.0
    phpstan/phpstan: 1.10.58
    phpstan/phpstan-deprecation-rules: 1.1.4
    phpstan/phpstan-phpunit: 1.3.15
    phpunit/php-code-coverage: 9.2.30
    phpunit/php-file-iterator: 3.0.6
    phpunit/php-invoker: 3.1.1
    phpunit/php-text-template: 2.0.4
    phpunit/php-timer: 5.0.3
    phpunit/phpunit: 9.6.16
    psr/cache: 3.0.0
    psr/container: 2.0.2
    psr/event-dispatcher: 1.0.0
    psr/http-client: 1.0.3
    psr/http-factory: 1.0.2
    psr/http-message: '2.0'
    psr/log: 3.0.0
    psy/psysh: v0.12.0
    ralouphie/getallheaders: 3.0.3
    react/promise: v3.1.0
    rector/rector: 0.19.8
    rvtraveller/qs-composer-installer: '1.2'
    sebastian/cli-parser: 1.0.1
    sebastian/code-unit: 1.0.8
    sebastian/code-unit-reverse-lookup: 2.0.3
    sebastian/comparator: 4.0.8
    sebastian/complexity: 2.0.3
    sebastian/diff: 4.0.5
    sebastian/environment: 5.1.5
    sebastian/exporter: 4.0.5
    sebastian/global-state: 5.0.6
    sebastian/lines-of-code: 1.0.4
    sebastian/object-enumerator: 4.0.4
    sebastian/object-reflector: 2.0.4
    sebastian/recursion-context: 4.0.5
    sebastian/resource-operations: 3.0.3
    sebastian/type: 3.2.1
    sebastian/version: 3.0.2
    seld/jsonlint: 1.10.2
    seld/phar-utils: 1.2.1
    seld/signal-handler: 2.0.2
    sirbrillig/phpcs-variable-analysis: v2.11.17
    slevomat/coding-standard: 8.14.1
    squizlabs/php_codesniffer: 3.8.1
    symfony/browser-kit: v6.4.3
    symfony/console: v6.4.3
    symfony/css-selector: v6.4.3
    symfony/dependency-injection: v6.4.3
    symfony/deprecation-contracts: v3.4.0
    symfony/dom-crawler: v6.4.3
    symfony/error-handler: v6.4.3
    symfony/event-dispatcher: v6.4.3
    symfony/event-dispatcher-contracts: v3.4.0
    symfony/filesystem: v6.4.3
    symfony/finder: v6.4.0
    symfony/http-foundation: v6.4.3
    symfony/http-kernel: v6.4.3
    symfony/lock: v6.4.3
    symfony/mailer: v6.4.3
    symfony/mime: v6.4.3
    symfony/phpunit-bridge: v6.4.3
    symfony/polyfill-ctype: v1.28.0
    symfony/polyfill-iconv: v1.28.0
    symfony/polyfill-intl-grapheme: v1.28.0
    symfony/polyfill-intl-idn: v1.28.0
    symfony/polyfill-intl-normalizer: v1.28.0
    symfony/polyfill-mbstring: v1.28.0
    symfony/polyfill-php72: v1.29.0
    symfony/polyfill-php73: v1.29.0
    symfony/polyfill-php80: v1.29.0
    symfony/polyfill-php81: v1.29.0
    symfony/polyfill-php82: v1.29.0
    symfony/polyfill-php83: v1.28.0
    symfony/process: v6.4.3
    symfony/psr-http-message-bridge: v6.4.3
    symfony/routing: v6.4.3
    symfony/serializer: v6.4.3
    symfony/service-contracts: v3.4.1
    symfony/string: v6.4.3
    symfony/translation-contracts: v3.4.1
    symfony/validator: v6.4.3
    symfony/var-dumper: v6.4.3
    symfony/var-exporter: v6.4.3
    symfony/yaml: v6.4.3
    theseer/tokenizer: 1.2.2
    twig/twig: v3.8.0
    webflo/drupal-finder: 1.2.2
    webmozart/assert: 1.11.0
