#!/usr/bin/env bash

if [ ! -d ~/.ssh ]; then
        mkdir ~/.ssh
fi

# Move SSH Config to not ask about host
cp ./.circleci/ssh_config ~/.ssh/config

ENV=${1:-DEV}
SSH_PORT=${SSH_PORT:-22}

varname=${ENV}_HOST
eval "ENV_HOST=\$$varname"

varname=${ENV}_USER
eval "ENV_USER=\$$varname"

varname=${ENV}_PORT
eval "ENV_PORT=\$$varname"

varname=${ENV}_PATH
eval "ENV_PATH=\$$varname"

# SSH_HOST: The host of the end machine to connect to
SSH_HOST="${ENV_HOST}"

# SSH_USER: Who should we connect as
SSH_USER="${ENV_USER}"

# SSH_PORT: The SSH Port to connect to
SSH_PORT="${ENV_PORT}"

# SSH_PATH: The location to rsync the files to
SSH_PATH="${ENV_PATH}"

if [[ "${SSH_HOST}" != "" ]] && [[ "${SSH_USER}" != "" ]] && [[ "${SSH_PORT}" != "" ]] && [[ "${SSH_PATH}" != "" ]]; then
    # Remove .git directory and do not transfer over.
    rm -rf .git

    rsync -avzI \
        -e "ssh -p ${SSH_PORT}" ${RSYNC_OPTIONS} \
        --delete \
        --exclude=".git" \
        --exclude="web/sites/default/files" \
        --exclude="web/sites/default/settings.local.php" \
        ~/repo/ ${SSH_USER}@${SSH_HOST}:${SSH_PATH}
fi
