#!/usr/bin/env bash

## Description: Create Cypress users
## Usage: cypress-users
## Example: "ddev cypress-users"
## OSTypes: darwin

# Abort if anything fails
set -e

echo "Create default admin user for Cypress tests."
ddev drush user-create cypress --mail="support+cypress@kanopi.com" --password="cypress" || true
ddev drush user-add-role administrator cypress
