#!/usr/bin/env bash

## Description: Install the node packages for cypress on the developers local machine
## Usage: install-cypress
## Example: "ddev install-cypress"
## OSTypes: darwin

# Make sure NVM works
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

CYPRESS_TESTS="/tests/cypress"
cd ${DDEV_APPROOT}/${CYPRESS_TESTS}
NODE_VERSION=$(cat ${DDEV_APPROOT}/${CYPRESS_TESTS}/.nvmrc)
nvm install $NODE_VERSION
nvm use
npm ci
