#!/usr/bin/env bash

## Description: Runs composer install and database refresh.
## Usage: rebuild
## Example: "ddev rebuild"
## OSTypes: darwin

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'

# Install dependencies.
echo -e "\n${yellow} Composer install. ${NC}"
echo -e "${green}${divider}${NC}"
ddev composer install

# Database.
ddev refresh
