#!/usr/bin/env bash

## Description: Get the database.
## Usage: refresh
## Example: "ddev refresh"
## OSTypes: darwin

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'

ENVIRONMENT=${1:-"$hostingenv"}

# Database.
echo -e "\n${yellow} Get database from Pantheon. ${NC}"
echo -e "${green}${divider}${NC}"
ddev pull pantheon --skip-files --y --env=${ENVIRONMENT}

cd ${DDEV_APPROOT}/${DDEV_DOCROOT}

echo "Update Drupal DB"
fin drush updatedb -y

echo "Clear cache"
fin drush cr -y
