version: "2.1"

services:
  cli:
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - THEME
      - THEMENAME
      - MIGRATE_DB_SOURCE
      - MIGRATE_DB_ENV
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro

  solr:
    image: "devkteam/solr:8"
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/opt/solr/server/solr/configsets/solr8/conf

  node:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    hostname: node
    image: devkteam/node:latest
    platform: linux/amd64
    environment:
      - THEME
      - THEMENAME
      - NODE_OPTIONS
    expose:
      - 6006
    labels:
      - io.docksal.virtual-host=storybook.${VIRTUAL_HOST},storybook.${VIRTUAL_HOST}.*
      - io.docksal.virtual-port=6006
