version: "2.1"

services:
  cli:
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - THEME
      - THEMENAME
      - MIGRATE_DB_SOURCE
      - MIGRATE_DB_ENV
      # Manually compile Chromium for Critical.
      - PUPPETEER_SKIP_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro
  solr:
    image: "devkteam/solr:8"
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/opt/solr/server/solr/configsets/solr8/conf
