#!/bin/bash

set -eo pipefail

#
# This script deploys the build artifact to Pantheon.
# On the master branch the dev environment is used.
# Otherwise a multidev environment is used.
#

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Wake up the dev environment
terminus -n env:wake "$TERMINUS_SITE.dev"

# Delete old multidev environments associated
# with PRs that has been merged or closed.
terminus -n build:env:delete:pr $TERMINUS_SITE --yes
terminus -n build:env:delete:ci $TERMINUS_SITE --yes

if [[ $CI_BRANCH != "main" ]]
then
  # Create a new multidev environment (or push to an existing one)
  terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes
else
  # Push to the dev environment
  terminus -n build:env:push "$TERMINUS_SITE.dev" --yes
fi

# Clear Drupal cache
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- cr

# Import config
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- config-import --yes


# Update the Drupal database
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y


# Clear Drupal cache
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- cr

# Clear the environment cache
terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV

# Ensure secrets are set
terminus -n secrets:set "$TERMINUS_SITE.$TERMINUS_ENV" token "$GITHUB_TOKEN" --file='github-secrets.json' --clear --skip-if-empty

# Delete old multidev environments associated
# with a PR that has been merged or closed.
terminus -n build:env:delete:pr $TERMINUS_SITE --yes
