_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  access_unpublished: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  automated_cron: 0
  block: 0
  block_class: 0
  block_content: 0
  block_field: 0
  bootstrap_layout_classes: 0
  breakpoint: 0
  checklistapi: 0
  ckeditor5: 0
  clamav: 0
  config: 0
  content_moderation: 0
  critical_css: 0
  crop: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  element_class_formatter: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ribbon: 0
  field: 0
  field_formatter: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  focal_point: 0
  gin_login: 0
  gin_toolbar: 0
  google_tag: 0
  help: 0
  image: 0
  imagemagick: 0
  inline_entity_form: 0
  launch_checklist: 0
  layout_discovery: 0
  layout_options: 0
  link: 0
  linkit: 0
  media: 0
  media_library: 0
  media_library_edit: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  mysql: 0
  node: 0
  nomarkup: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  path: 0
  path_alias: 0
  quick_node_clone: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  resource_hints: 0
  responsive_image: 0
  responsive_tables_filter: 0
  saplings_custom: 0
  scanner: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  schema_article: 0
  schema_metatag: 0
  seckit: 0
  security_review: 0
  seo_checklist: 0
  shortcut: 0
  simple_sitemap: 0
  sitemap: 0
  sophron: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_or: 0
  toolbar: 0
  tour: 0
  ui_patterns: 0
  ui_patterns_ds: 0
  ui_patterns_field_formatters: 0
  ui_patterns_layouts: 0
  ui_patterns_library: 0
  ui_patterns_settings: 0
  ui_skins: 0
  ui_styles: 0
  ultimate_cron: 0
  unused_modules: 0
  update: 0
  user: 0
  view_unpublished: 0
  views_ui: 0
  viewsreference: 0
  workflows: 0
  ds: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  paragraphs: 11
  publication_date: 99
  minimal: 1000
theme:
  stark: 0
  claro: 0
  gin: 0
  ui_suite_bootstrap: 0
  saplings_child: 0
profile: minimal
