#!/usr/bin/env bash

set -e;

#: exec_target = cli

SITE_ROOT="${PROJECT_ROOT}/${DOCROOT}"

# Dynamically set Behat configuration parameters
#export BEHAT_PARAMS='{"extensions" : {"Drupal\\DrupalExtension" : {"drupal": { "drupal_root": "'$SITE_ROOT'" }, "drush" :   {  "root":  "'$SITE_ROOT'" }}}}'

echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo "Behat test site"
echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo

# Run the Behat tests
./vendor/bin/behat --config=tests/behat/behat-docksal.yml --strict --colors  "$@"