#!/usr/bin/env bash

## Run Cypress Commands
##
## Usage: fin cypress [command] [URL with no http(s)://]
## Defaults to //$VIRTUAL_HOST
##

# Abort if anything fails
set -e

# Make sure NVM works
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

cd ${PROJECT_ROOT}/tests/cypress
nvm use

ENVIRONMENT=${2:-"$VIRTUAL_HOST"}


CYPRESS_BASE_URL="http://${ENVIRONMENT}" ./node_modules/.bin/cypress  "$@"
