#!/usr/bin/env bash

#: exec_target = cli

## Run Gulp Commands on the theme
##
## Usage: fin gulp [arguments]
##

# Abort if anything fails
set -e

if [[ -n "${THEME_ROOT} "]]; then
  cd ${PROJECT_ROOT}/${DOCROOT}/${THEME_ROOT}
fi

gulp "$@"
