#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------
# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	# We disable email sending here so site-install does not return an error
	PHP_OPTIONS="-d sendmail_path=`which true`" \
		drush \
		site-install \
		-y \
		--site-name='My Drupal 8 Site' \
		--sites-subdir="default"
}

# Composer Install
composer_install ()
{
  cd $PROJECT_ROOT
  composer install
}

# Run Install Items
install_items ()
{
  composer_install
  fix_permissions
  site_install
}
#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Install the tmp directory.
if [[ ! -d ~/tmp ]]; then
  mkdir ~/tmp
fi

time install_items

count=$(ls -1 ${PROJECT_ROOT}/config/*.yml 2>/dev/null | wc -l)
if [[ $count -gt 0 ]]; then
  ${PROJECT_ROOT}/.docksal/commands/refresh
  ${PROJECT_ROOT}/.docksal/commands/site-build
else
  cd $DOCROOT_PATH
  # Export Configuration to config folder.
  drush cex -y
fi

# Project initialization steps
#-------------------------- END: Execution --------------------------------
