#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

fin=$(which fin)
[[ -f ${fin} ]] && source $fin

LEFTHOOK=$(which lefthook || true)
if [[ "${LEFTHOOK}" == "" ]]; then
  echo -e "${green_bg} Setup  ${NC}${green} Installing Lefthook...${NC}"
  sudo curl -fsSL -o /usr/local/bin/lefthook "https://github.com/evilmartians/lefthook/releases/download/v0.7.7/lefthook_0.7.7_MacOS_x86_64"
  sudo chmod +x /usr/local/bin/lefthook
fi

# Initializing Githooks
echo -e "${green_bg} Setup  ${NC}${green} Initializing githooks...${NC}"
lefthook install

echo "Install SSL certs...";
fin addon install mkcert --global
fin mkcert create

echo "Install Docksal Pull Command";
fin addon install --global pull

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
fin reset -f

echo "Waiting 10s for MySQL to initialize...";
sleep 10

# Site initialization
echo -e "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"
# This runs inside cli using http://docs.docksal.io/en/v1.4.0/fin/custom-commands/#executing-commands-inside-cli
fin init-site
fin install-theme-tools

echo -e "${green_bg} Step 3 ${NC}${green} Pulling data from hosting...${NC}"
fin refresh

echo -en "${green_bg} DONE! ${NC} "
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
