#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall theme
##
## Usage: fin emulsify

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'

divider='===================================================\n'
check='\xE2\x9C\x85'
construction='\xF0\x9F\x9A\xA7'
crossmark='\xE2\x9D\x8C'
hospital='\xF0\x9F\x8F\xA5'
party='\xF0\x9F\x8E\x88 \xF0\x9F\x8E\x89 \xF0\x9F\x8E\x8A'
reverseparty='\xF0\x9F\x8E\x8A \xF0\x9F\x8E\x89 \xF0\x9F\x8E\x88'
rocket='\xF0\x9F\x9A\x80'
silhouette='\xF0\x9F\x91\xA4'
lightning='\xE2\x9A\xA1'
drop='\xF0\x9F\x92\xA7'
shark='\xF0\x9F\xA6\x88'
gear='\xEF\xB8\x8F'
watch_command='fin npm run develop'

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="${SITE_DIRECTORY}"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
FULL_THEME_PATH="${DOCROOT_PATH}/themes/custom/${THEME}"
#-------------------------- Execution -------------------------------------

# Theme initialization.
echo -e "\n${yellow} ${shark} Building tools needed for the theme. ${shark}${NC}\n"
echo -e "${NC}This should take ~8 minutes on an empty cache.${NC}"
echo -e "${green}${divider}${NC}"

# Critical.
echo -e "\n${yellow} ${hospital} Installing tools needed for Critical ${hospital}${NC}"
echo -e "${green}${divider}${NC}"
sudo apt update
sudo apt install -yq --no-install-recommends dh-autoreconf libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3

# Move to the theme.
echo -e "\n${yellow} ${rocket} To the theme! ${rocket}${NC}"
echo -e "${yellow} ${FULL_THEME_PATH}${NC}"
echo -e "${green}${divider}${NC}"
cd ${FULL_THEME_PATH}

# Check for and remove the 'node_modules' folder for good measure before we install.
if [ -d "$node_modules" ]; then
  echo "removing node_modules folder"
  rm -R node_modules
fi

# Runs NPM Install.
echo -e "\n${yellow} ${construction} Install NPM ${construction}${NC}"
echo -e "${green}${divider}${NC}"
source ~/.nvm/nvm.sh
source ~/.bashrc
echo "NVM version: $(nvm --version)"
NODE_VERSION=$(cat ${FULL_THEME_PATH}/.nvmrc)
echo "Theme node version: ${NODE_VERSION}"
nvm install ${NODE_VERSION}
nvm alias default ${NODE_VERSION}
nvm use
npm install

# Run Storybook Develop.
echo -e "\n${yellow} ${construction} Running Storybook Develop ${construction}${NC}"
echo -e "${green}${divider}${NC}"
npm run build

# Finish.
echo -e "\n${yellow} ${party} Theme rebuilt!!! ${reverseparty}${NC}"
echo -e "${NC}Run ${yellow}${watch_command}${NC} to watch${NC}"
echo -e "${NC}Then, storybook will run at ${yellow}http://storybook.${VIRTUAL_HOST}${NC}"
echo -e "${green}${divider}${NC}"
