#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall tools needed for critical CSS.
##
## Usage: fin install-critical-tools

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'

divider='===================================================\n'
check='\xE2\x9C\x85'
construction='\xF0\x9F\x9A\xA7'
crossmark='\xE2\x9D\x8C'
hospital='\xF0\x9F\x8F\xA5'
party='\xF0\x9F\x8E\x88 \xF0\x9F\x8E\x89 \xF0\x9F\x8E\x8A'
reverseparty='\xF0\x9F\x8E\x8A \xF0\x9F\x8E\x89 \xF0\x9F\x8E\x88'
rocket='\xF0\x9F\x9A\x80'
silhouette='\xF0\x9F\x91\xA4'
lightning='\xE2\x9A\xA1'
drop='\xF0\x9F\x92\xA7'
shark='\xF0\x9F\xA6\x88'
gear='\xEF\xB8\x8F'
critical_command='fin critical'

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="${SITE_DIRECTORY}"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
FULL_THEME_PATH="${DOCROOT_PATH}/${THEME}"
#-------------------------- Execution -------------------------------------

# Critical.
echo -e "\n${yellow} ${hospital} Installing tools needed for Critical ${hospital}${NC}"
echo -e "${green}${divider}${NC}"
sudo apt-get --allow-releaseinfo-change update
sudo apt-get install -yq --no-install-recommends libgbm1 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3

# Finish.
echo -e "\n${yellow} ${party} Critical CSS Tools installed. ${reverseparty}${NC}"
echo -e "${NC}@TODO Move Critical out of theme folder.${NC}"
echo -e "${NC}Run ${yellow}${critical_command}${NC} to compile critical css.${NC}"
echo -e "${green}${divider}${NC}"
