#!/usr/bin/env bash

## Install the theme tools in the container
##
## Usage: fin install-theme-tools
##
## Should just need to be run once.

# Abort if anything fails
set -e

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

echo "Installing theme tools"
cd "${DOCROOT_PATH}/themes/custom/${THEME}"
fin exec nvm install 12
fin exec nvm alias default 12
fin npm install
fin gulp build
