#!/usr/bin/env bash

## Create and configure the migration database.
##
## Usage: fin migrate-prep-db

# Abort if anything fails
set -e

## Create local source database to facilitate migrations.
fin db create migrate

## Populate source database from a multidev.
fin pull db --db-name=migrate -y --hosting-platform=${hostingplatform} --hosting-site=${MIGRATE_DB_SOURCE} --hosting-env=${MIGRATE_DB_ENV}
