#!/usr/bin/env bash

#: exec_target = cli

## Run NPX Commands
##
## Usage: fin npx [arguments]
##

# Abort if anything fails
set -e

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

cd ${DOCROOT_PATH}/${THEME}

npx "$@"
