#!/usr/bin/env bash

#: exec_target = cli

## Apply a Drupal Recipe that has been installed using composer.
##
## Usage: fin recipe-apply [name]
##

# Abort if anything fails
set -e

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

cd ${DOCROOT_PATH}

php core/scripts/drupal recipe recipes/contrib/"$@"

drush cr
