#!/usr/bin/env bash

## One time Composer configuration for Drupal recipes.
##
## Usage: fin recipe-configure

# Abort if anything fails
set -e

#-------------------------- Helper functions ------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'

divider='===================================================\n'
party='\xF0\x9F\x8E\x88 \xF0\x9F\x8E\x89 \xF0\x9F\x8E\x8A'
reverseparty='\xF0\x9F\x8E\x8A \xF0\x9F\x8E\x89 \xF0\x9F\x8E\x88'
require_command='fin composer require org/recipe-name'
apply_command='fin recipe-apply recipe-name'
unpack_command='fin recipe-unpack org/recipe-name'

#-------------------------- Execution ------------------------------

# Configure the location recipes go when required.
fin composer config extra.installer-paths --merge --json '{"/recipes/{$name}": ["type:drupal-recipe"]}'

# Requires Drupal Recipe Unpack.
fin composer config allow-plugins.ewcomposer/unpack true
fin composer config repo.recipe-unpack vcs https://gitlab.ewdev.ca/yonas.legesse/drupal-recipe-unpack.git
fin composer require ewcomposer/unpack:1.x-dev@dev

# Complete
echo -e "\n${yellow} ${party} Your project is now ready to apply recipes! ${reverseparty}${NC}"
echo -e "Run ${yellow}${require_command}${NC} to require a recipe."
echo -e "Run ${yellow}${apply_command}${NC} to apply a recipe."
echo -e "Run ${yellow}${unpack_command}${NC} to unpack the recipe's dependencies to the project's composer.json"
echo -e "Be sure to export configuration after recipe application to capture its config in your site."
echo -e "${green}${divider}${NC}"
