#!/usr/bin/env bash

#: exec_target = cli

## Apply a Drupal Recipe that has been installed using composer.
## For contrib recipes:
## Example: fin recipe-apply ../recipes/recipe-name
## For core recipes:
## Example: fin recipe-apply core/recipes/standard
##

# Abort if anything fails
set -e

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

cd ${DOCROOT_PATH}

drush cr
php core/scripts/drupal recipe "$@"
drush cr
