#!/usr/bin/env bash

#: exec_target = cli

## Renames the download of the repo https://github.com/kanopi/kdcl_basic to the name of the theme set in THEME variable.

# Abort if anything fails
set -e

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
THEME_ROOT="${PROJECT_ROOT}/${DOCROOT}/themes/custom"

# Rename git download
cd $THEME_ROOT
GIT_DIR_NAME=$(find ./* -maxdepth 0 -type d)

echo $GIT_DIR_NAME
cd $GIT_DIR_NAME

echo "Rename root theme files."
rename "s/^kdcl_basic/$THEME/" kdcl_basic*

echo "Update text in files"
find ./ -type f -exec sed -i "s/kdcl_basic/$THEME/g" {} \;

echo "Remove 'dist' ignore in theme gitignore.  This is for circleci deployments to work correctly."
sed -i 's/dist//g' .gitignore

echo "Rename folder in components"
cd components
mv kdcl_basic "$THEME"

echo "Raname github folder"
cd $THEME_ROOT
mv "$GIT_DIR_NAME" "$THEME"

echo "Done  :)"

