#!/usr/bin/env bash

#: exec_target = cli

# Abort if anything fails
set -e

#-------------------------- Settings ---------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY=${SITE_DIRECTORY:-default}
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#------------------------- END: Settings -----------------------------

#-------------------------- Functions --------------------------------

# Composer Install
composer_install ()
{
  cd $PROJECT_ROOT
  echo "Running Composer Install..."
  composer install
}

gulp_install ()
{
  if [[ -n "${THEME_ROOT} " ]]; then
    cd ${PROJECT_ROOT}/${DOCROOT}/${THEME_ROOT}
  fi
  echo "Running Gulp Tasks on theme"
  npm i -g npm@latest
  npm i -g gulp-cli
  npm install
  gulp
}

#-------------------------- END: Functions --------------------------------

time composer_install

cd ${DOCROOT_PATH}

echo "Running Update.php..."
drush updatedb -y

echo "Importing Configuration..."
drush cim --yes

echo "Running Drush Cache-Rebuild"
drush cr

time gulp_install

cd ${DOCROOT_PATH}
echo "Running Drush Cache-Rebuild (again)"
drush cr
