#!/usr/bin/env bash

#: exec_target = cli

# Abort if anything fails
set -e

SITE_DIRECTORY=${SITE_DIRECTORY:-default}

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

cd ${PROJECT_ROOT}
echo "Running Composer Install..."
composer install

cd ${DOCROOT_PATH}

echo "Running Update.php..."
drush updatedb -y

echo "Importing Configuration..."
drush cim --yes

echo "Running Drush Cache-Rebuild"
drush cr

echo "Running Gulp Tasks on theme"
cd ${PROJECT_ROOT}/web/themes/custom/site_theme
npm i -g npm@latest
npm i -g gulp-cli
npm install
gulp sass
drush cr
