#!/usr/bin/env bash

## Description: Runs NPM commands on the theme.
## Usage: npm
## Example: ddev npm

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# Define paths.
FULL_THEME_PATH="/var/www/html/${DDEV_DOCROOT}/${THEME}"

#-------------------------- Execution -------------------------------------

cd ${FULL_THEME_PATH}

npm "$@"
