#!/usr/bin/env bash

## Description: Runs NPX commands on the theme.
## Usage: npx
## Example: ddev npx

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# Define paths.
FULL_THEME_PATH="/var/www/html/${DDEV_DOCROOT}/${THEME}"

#-------------------------- Execution -------------------------------------

cd ${FULL_THEME_PATH}

npx "$@"
