#!/usr/bin/env bash

#: exec_target = cli

## Run Gulp Commands on the theme
##
## Usage: fin gulp [arguments]
##

# Abort if anything fails
set -e

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

cd ${DOCROOT_PATH}/themes/custom/${THEME}

./node_modules/.bin/gulp "$@"
